name: Deploy
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint
      - run: bun test
      - run: bun run build
      - name: Upload build artifacts
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist/
          retention-days: 1

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # - name: Download build artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: github-pages
      #     path: dist/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
